-- Custom constraints
CREATE DOMAIN EVM_ADDRESS AS VARCHAR(42) CHECK(
VALUE ~* '^0x[a-fA-F\d]{40}$'
);
CREATE DOMAIN EVM_BEACON_ID AS VARCHAR(66) CHECK(
VALUE ~* '^0x[a-fA-F\d]{64}$'
);
CREATE DOMAIN EVM_XPUB AS VARCHAR(109) CHECK(
VALUE ~* '^0x[a-fA-F\d]{107}$'
);
CREATE EXTENSION IF NOT EXISTS pgcrypto;